services:

  pyrlang: &pyrlang
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.python

  elixir:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.elixir
    hostname: elixir.local
    environment:
      - PYTHON_NODES=py@pyrlang-1.local,py@pyrlang-2.local

  python-pyrlang-1:
    <<: *pyrlang
    hostname: pyrlang-1.local
    environment:
      - ERLANG_NODE=erl@elixir.local
      - MY_NODE=py@pyrlang-1.local

  python-pyrlang-2:
    <<: *pyrlang
    hostname: pyrlang-2.local
    environment:
      - ERLANG_NODE=erl@elixir.local
      - MY_NODE=py@pyrlang-2.local